### ISSUE TITLE
Browser back button should behave like the "Back" button on the page

### ISSUE THREAD

**Issue by jcfr** [girder/legacy-resonant-website#9] opened 2015-09-28 15:03 UTC
To reproduce:
- Go to https://github.com/Kitware/resonant-website
- Click on http://resonant.kitware.com  at the top of the github page associated with `resonant-website` project
- Click on any example
- Click on the browser "Back" button ... you ends up back on the github page

**Comment by zachmullen** [comment] 2015-09-28 15:07
Think this is a duplicate of #3. We can probably just get away with some good old fashioned anchor tags.

**Comment by jeffbaumes** [comment] 2015-10-05 12:51
@zachmullen care to give it a go? Not sure exactly how to implement this in the way you suggest.

**Comment by zachmullen** [comment] 2015-10-05 13:12
Sure

**Closed as completed** 2015-10-05 16:47 UTC
